[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
Flask-SQLAlchemy = "^2.4.4"
Flask-Login = "^0.5.0"
auth = "^0.5.3"
views = "^0.3"
